package com.crc.weixin.entity;

import java.io.Serializable;

public class User implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER.USER_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String userNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER.USER_NAME
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER.PASSWORD
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER.STATUS
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER.CREATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column USER.UPDATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER.USER_NO
	 * @return  the value of USER.USER_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getUserNo() {
		return userNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER.USER_NO
	 * @param userNo  the value for USER.USER_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER.USER_NAME
	 * @return  the value of USER.USER_NAME
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER.USER_NAME
	 * @param userName  the value for USER.USER_NAME
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER.PASSWORD
	 * @return  the value of USER.PASSWORD
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER.PASSWORD
	 * @param password  the value for USER.PASSWORD
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER.STATUS
	 * @return  the value of USER.STATUS
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER.STATUS
	 * @param status  the value for USER.STATUS
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER.CREATE_DATE
	 * @return  the value of USER.CREATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER.CREATE_DATE
	 * @param createDate  the value for USER.CREATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column USER.UPDATE_DATE
	 * @return  the value of USER.UPDATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column USER.UPDATE_DATE
	 * @param updateDate  the value for USER.UPDATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}
}