package com.crc.weixin.dao.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.crc.weixin.entity.Menu;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated Tue Jun 21 14:31:46 CST 2016
     */
    int deleteByPrimaryKey(String menuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated Tue Jun 21 14:31:46 CST 2016
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated Tue Jun 21 14:31:46 CST 2016
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated Tue Jun 21 14:31:46 CST 2016
     */
    Menu selectByPrimaryKey(String menuNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated Tue Jun 21 14:31:46 CST 2016
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated Tue Jun 21 14:31:46 CST 2016
     */
    int updateByPrimaryKey(Menu record);
    
    /**
     * 根据菜单父类编号获取集合对象
     * @param menuNo
     * @return
     */
    List<Menu> selectByAccountNoAndParent(@Param("accountNo")String accountNo,@Param("menuNo")String menuNo);
}