package com.crc.weixin.dao.mappers;

import java.util.List;

import com.crc.weixin.entity.Account;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int deleteByPrimaryKey(String accountNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int insert(Account account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int insertSelective(Account account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    Account selectByPrimaryKey(String accountNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int updateByPrimaryKeySelective(Account account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int updateByPrimaryKey(Account account);
    
    /**
     * 根据指定的主键批量删除数据
     * @param accountNos
     * @return
     */
    int batchDeleteByAccountNos(List<String> accountNos);
}