package com.crc.weixin.dao.mappers;

import com.crc.weixin.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int deleteByPrimaryKey(String userNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    User selectByPrimaryKey(String userNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbggenerated Mon Jun 20 17:12:18 CST 2016
     */
    int updateByPrimaryKey(User record);
}