package com.crc.weixin.entity;

import java.io.Serializable;

public class Menu implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.MENU_NO
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String menuNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.ACCOUNT_NO
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String accountNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.PARENT
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String parent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.NAME
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.TYPE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.MENU_KEY
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String menuKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.URL
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.MEDIA_ID
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String mediaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.CREATE_DATE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MENU.UPDATE_DATE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	private String updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.MENU_NO
	 * @return  the value of MENU.MENU_NO
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getMenuNo() {
		return menuNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.MENU_NO
	 * @param menuNo  the value for MENU.MENU_NO
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setMenuNo(String menuNo) {
		this.menuNo = menuNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.ACCOUNT_NO
	 * @return  the value of MENU.ACCOUNT_NO
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getAccountNo() {
		return accountNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.ACCOUNT_NO
	 * @param accountNo  the value for MENU.ACCOUNT_NO
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.PARENT
	 * @return  the value of MENU.PARENT
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getParent() {
		return parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.PARENT
	 * @param parent  the value for MENU.PARENT
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setParent(String parent) {
		this.parent = parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.NAME
	 * @return  the value of MENU.NAME
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.NAME
	 * @param name  the value for MENU.NAME
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.TYPE
	 * @return  the value of MENU.TYPE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.TYPE
	 * @param type  the value for MENU.TYPE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.MENU_KEY
	 * @return  the value of MENU.MENU_KEY
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getMenuKey() {
		return menuKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.MENU_KEY
	 * @param menuKey  the value for MENU.MENU_KEY
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setMenuKey(String menuKey) {
		this.menuKey = menuKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.URL
	 * @return  the value of MENU.URL
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.URL
	 * @param url  the value for MENU.URL
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.MEDIA_ID
	 * @return  the value of MENU.MEDIA_ID
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getMediaId() {
		return mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.MEDIA_ID
	 * @param mediaId  the value for MENU.MEDIA_ID
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setMediaId(String mediaId) {
		this.mediaId = mediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.CREATE_DATE
	 * @return  the value of MENU.CREATE_DATE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.CREATE_DATE
	 * @param createDate  the value for MENU.CREATE_DATE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MENU.UPDATE_DATE
	 * @return  the value of MENU.UPDATE_DATE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public String getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MENU.UPDATE_DATE
	 * @param updateDate  the value for MENU.UPDATE_DATE
	 * @mbggenerated  Tue Jun 21 17:02:15 CST 2016
	 */
	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((accountNo == null) ? 0 : accountNo.hashCode());
		result = prime * result + ((createDate == null) ? 0 : createDate.hashCode());
		result = prime * result + ((mediaId == null) ? 0 : mediaId.hashCode());
		result = prime * result + ((menuKey == null) ? 0 : menuKey.hashCode());
		result = prime * result + ((menuNo == null) ? 0 : menuNo.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((parent == null) ? 0 : parent.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		result = prime * result + ((updateDate == null) ? 0 : updateDate.hashCode());
		result = prime * result + ((url == null) ? 0 : url.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Menu other = (Menu) obj;
		if (accountNo == null) {
			if (other.accountNo != null)
				return false;
		} else if (!accountNo.equals(other.accountNo))
			return false;
		if (createDate == null) {
			if (other.createDate != null)
				return false;
		} else if (!createDate.equals(other.createDate))
			return false;
		if (mediaId == null) {
			if (other.mediaId != null)
				return false;
		} else if (!mediaId.equals(other.mediaId))
			return false;
		if (menuKey == null) {
			if (other.menuKey != null)
				return false;
		} else if (!menuKey.equals(other.menuKey))
			return false;
		if (menuNo == null) {
			if (other.menuNo != null)
				return false;
		} else if (!menuNo.equals(other.menuNo))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (parent == null) {
			if (other.parent != null)
				return false;
		} else if (!parent.equals(other.parent))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		if (updateDate == null) {
			if (other.updateDate != null)
				return false;
		} else if (!updateDate.equals(other.updateDate))
			return false;
		if (url == null) {
			if (other.url != null)
				return false;
		} else if (!url.equals(other.url))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Menu [menuNo=" + menuNo + ", accountNo=" + accountNo + ", parent=" + parent + ", name=" + name
				+ ", type=" + type + ", menuKey=" + menuKey + ", url=" + url + ", mediaId=" + mediaId + ", createDate="
				+ createDate + ", updateDate=" + updateDate + "]";
	}
    
    
}