package com.crc.weixin.entity;

import java.io.Serializable;

public class Account implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.ACCOUNT_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String accountNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.USER_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String userNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.ACCOUNT
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.NAME
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.API_URL
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String apiUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.TYPE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.TOKEN
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.APP_ID
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.APP_SECRET
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String appSecret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.CREATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACCOUNT.UPDATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	private String updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.ACCOUNT_NO
	 * @return  the value of ACCOUNT.ACCOUNT_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getAccountNo() {
		return accountNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.ACCOUNT_NO
	 * @param accounto  the value for ACCOUNT.ACCOUNT_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.USER_NO
	 * @return  the value of ACCOUNT.USER_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getUserNo() {
		return userNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.USER_NO
	 * @param userNo  the value for ACCOUNT.USER_NO
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.ACCOUNT
	 * @return  the value of ACCOUNT.ACCOUNT
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.ACCOUNT
	 * @param account  the value for ACCOUNT.ACCOUNT
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.NAME
	 * @return  the value of ACCOUNT.NAME
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.NAME
	 * @param name  the value for ACCOUNT.NAME
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.API_URL
	 * @return  the value of ACCOUNT.API_URL
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getApiUrl() {
		return apiUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.API_URL
	 * @param apiUrl  the value for ACCOUNT.API_URL
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setApiUrl(String apiUrl) {
		this.apiUrl = apiUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.TYPE
	 * @return  the value of ACCOUNT.TYPE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.TYPE
	 * @param type  the value for ACCOUNT.TYPE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.TOKEN
	 * @return  the value of ACCOUNT.TOKEN
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.TOKEN
	 * @param token  the value for ACCOUNT.TOKEN
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.APP_ID
	 * @return  the value of ACCOUNT.APP_ID
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.APP_ID
	 * @param appId  the value for ACCOUNT.APP_ID
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.APP_SECRET
	 * @return  the value of ACCOUNT.APP_SECRET
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getAppSecret() {
		return appSecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.APP_SECRET
	 * @param appSecret  the value for ACCOUNT.APP_SECRET
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setAppSecret(String appSecret) {
		this.appSecret = appSecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.CREATE_DATE
	 * @return  the value of ACCOUNT.CREATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.CREATE_DATE
	 * @param createDate  the value for ACCOUNT.CREATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACCOUNT.UPDATE_DATE
	 * @return  the value of ACCOUNT.UPDATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public String getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACCOUNT.UPDATE_DATE
	 * @param updateDate  the value for ACCOUNT.UPDATE_DATE
	 * @mbggenerated  Mon Jun 20 17:12:18 CST 2016
	 */
	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((account == null) ? 0 : account.hashCode());
		result = prime * result + ((accountNo == null) ? 0 : accountNo.hashCode());
		result = prime * result + ((apiUrl == null) ? 0 : apiUrl.hashCode());
		result = prime * result + ((appId == null) ? 0 : appId.hashCode());
		result = prime * result + ((appSecret == null) ? 0 : appSecret.hashCode());
		result = prime * result + ((createDate == null) ? 0 : createDate.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((token == null) ? 0 : token.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		result = prime * result + ((updateDate == null) ? 0 : updateDate.hashCode());
		result = prime * result + ((userNo == null) ? 0 : userNo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Account other = (Account) obj;
		if (account == null) {
			if (other.account != null)
				return false;
		} else if (!account.equals(other.account))
			return false;
		if (accountNo == null) {
			if (other.accountNo != null)
				return false;
		} else if (!accountNo.equals(other.accountNo))
			return false;
		if (apiUrl == null) {
			if (other.apiUrl != null)
				return false;
		} else if (!apiUrl.equals(other.apiUrl))
			return false;
		if (appId == null) {
			if (other.appId != null)
				return false;
		} else if (!appId.equals(other.appId))
			return false;
		if (appSecret == null) {
			if (other.appSecret != null)
				return false;
		} else if (!appSecret.equals(other.appSecret))
			return false;
		if (createDate == null) {
			if (other.createDate != null)
				return false;
		} else if (!createDate.equals(other.createDate))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (token == null) {
			if (other.token != null)
				return false;
		} else if (!token.equals(other.token))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		if (updateDate == null) {
			if (other.updateDate != null)
				return false;
		} else if (!updateDate.equals(other.updateDate))
			return false;
		if (userNo == null) {
			if (other.userNo != null)
				return false;
		} else if (!userNo.equals(other.userNo))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Account [accountNo=" + accountNo + ", userNo=" + userNo + ", account=" + account + ", name=" + name
				+ ", apiUrl=" + apiUrl + ", type=" + type + ", token=" + token + ", appId=" + appId + ", appSecret="
				+ appSecret + ", createDate=" + createDate + ", updateDate=" + updateDate + "]";
	}
	
	
}